### PR TITLE
Docker build of NEURON+Python Mybinder launcher of result.

### PR DESCRIPTION
**Pull request by russelljjarvis**
Since building the pre-requisites for your model/code is tough. I put in a Dockerfile to automate it, and I demonstrated easy jupyter-notebook deployment with my binder.

### CODE REVIEW

**Comment by chlubba** [comment]
Thanks for investing the time to make PyPNS more accessible Russell, sounds like a great idea. I’ll take a look this weekend and merge if it works.

**Comment by russelljjarvis** [comment]
Hi @chlubba, This is the same idea as before but I also use travis.yml to objectively validate the build. One thing I found was that ```matplotlib.use("tkagg")``` was a lot harder to reproduce than just `matplotlib.use("agg")` I wonder if the `tk` package really offers any advantage over just regular 'agg'?

**Comment by chlubba** [comment]
Hi @russelljjarvis, 

the docker seems to work very well, thanks again for investing the time! I accepted the pull request and merged your version into my main repository.

tkagg might not be necessary either. I remember it being relevant only for specific plots.

Best,
Carl

**Comment by russelljjarvis** [comment]
Hi Carl,

No problems. I hope these adaptions make NEURON+Python more accessible for some. It is also possible to make the Dockerfile build parallel NEURON too. 

As time goes on and if you get the chance you may want to redirect the links for generating the travis build status and the mybinder to your specific git repository. I believe they point to mine now which is good, but if I fail to pull any of your future code commits then both builds will be a reflection of an older product and not a current reflection. Travis and MyBinder are both free. My Binder does not require a login and you can create a badge specific to your git repository from the front page (although the build may take 15 minutes).

**Comment by chlubba** [comment]
Thanks Russel! I now redirected these to my repository. Let me know, if you add anything in your forked version, I'll certainly merge it into my branch.

**Pull request merged**
